# Generated by Django 3.0.5 on 2020-09-07 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, unique=True)),
                ('connect', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('isdelete', models.BooleanField(default=False)),
                ('access_count', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('file', models.ImageField(upload_to='upload/images/')),
            ],
            options={
                'db_table': 'post_model',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ScardModel',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stuone.StudentModel')),
                ('major', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
