# Generated by Django 3.0.5 on 2020-09-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stusix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='photo',
            field=models.ImageField(upload_to='imgs'),
        ),
    ]
